# Generated by Django 4.2.6 on 2023-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='cover_image.jpg', upload_to='cover_image/'),
        ),
    ]
